
name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Using a custom color configuration that works well in both modes
          # #4F94CD - Steel Blue for the snake
          # #305F72, #5899B5, #84C6D9, #A8D9E7, #DAEAF1 - Blues/Teals for dots
          outputs: |
            dist/snake.svg?color_snake=#4F94CD&color_dots=#1E1E1E,#84C6D9,#5899B5,#305F72,#DAEAF1

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
